// Mnemosyne — Sales Factory C4.2: server-side prohibited-content scanner (Aegis prerequisite for persistence).
//
// Backstop over model-authored draft slots. The generator is already instructed not to emit these, but a
// scanner is required before any draft is PERSISTED. Used two ways:
//   - /api/generate-contract: run after assembly, surface hits as warnings (draft still returned, review-only).
//   - /api/save-document: run before persistence, REFUSE the save if not clean (no row written).
//
// Categories: vendor/product brand names (the no-vendor-specifics rule), AI-disclosure phrasing (the
// no-AI-disclosure-in-binding-docs rule), leftover assembly markers, and high-signal secret patterns.
//
// Brand list is deliberately CONSERVATIVE — only unambiguous product/vendor tokens, so a legitimate English
// word ("render", "react to", "resend the email") can't wrongly block a save. The model instruction is the
// first line of defense; this is the backstop.

export type ScanHit = { category: 'brand' | 'ai_disclosure' | 'marker' | 'secret'; match: string }
export type ScanResult = { clean: boolean; hits: ScanHit[] }

// Unambiguous vendor/product brands that must not appear in client-facing contract text (use functional
// categories instead — "a managed database platform", not the brand).
const BRANDS = /\b(supabase|cloudflare|stripe|sendgrid|mailchimp|openai|chatgpt|anthropic|vercel|netlify|heroku|twilio|postgresql|firebase|mongodb|\bAWS\b|amazon web services|microsoft azure|google cloud platform)\b/i

// AI-disclosure phrasing only (NOT the topic "artificial intelligence", so an AI-subject project isn't blocked).
const AI_DISCLOSURE = /\b(ai[- ]?generated|generated by ai|ai[- ]?assisted|drafted by ai|created using ai|with the assistance of (ai|artificial intelligence)|powered by (a )?(large language model|llm)|this (document|agreement|draft|contract)[^.]{0,40}\b(generated|created|drafted)\b[^.]{0,20}\bai\b)\b/i

const MARKERS = /\{\{[^}]*\}\}|<<<SLOT|<<<ENDSLOT/

const SECRET = /sk_(live|test)_[A-Za-z0-9]{8,}|\bsbp_[A-Za-z0-9]{20,}|\bsb_(secret|publishable)_[A-Za-z0-9_]+|eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{6,}|AIza[0-9A-Za-z_-]{30,}|\bAKIA[0-9A-Z]{16}\b|\bghp_[A-Za-z0-9]{30,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|xox[baprs]-[A-Za-z0-9-]{8,}/

export function scanContract(md: string): ScanResult {
  const hits: ScanHit[] = []
  const b = md.match(BRANDS); if (b) hits.push({ category: 'brand', match: b[0] })
  const a = md.match(AI_DISCLOSURE); if (a) hits.push({ category: 'ai_disclosure', match: a[0].slice(0, 60) })
  const m = md.match(MARKERS); if (m) hits.push({ category: 'marker', match: m[0].slice(0, 40) })
  const s = md.match(SECRET); if (s) hits.push({ category: 'secret', match: s[0].slice(0, 12) + '…' })
  return { clean: hits.length === 0, hits }
}
