-- Mnemosyne — 0013: C4.2 generated-draft persistence. Additive. UNAPPLIED until Aegis QC + Jesse go.
--
-- Adds:
--   * documents.origin  — 'ingested' (the C1 finals, default) vs 'draft' (generated by C4.1). Lets the UI
--     distinguish, and lets save_document be INSERT-ONLY so a generated draft can NEVER collide with or
--     overwrite an ingested final contract.
--   * save_document(p_payload, p_actor, p_audit) — SECURITY DEFINER, empty search_path, service_role-only.
--     Atomic: inserts a NEW draft documents row + its chunks + an audit entry in one transaction. Actor must
--     be an ACTIVE team member (fail closed). Mirrors remember_memory's chunk discipline (contiguous index,
--     768-dim, unit-normalized, pinned embedding_model, bounded fan-out). NO update/delete/overwrite path.

alter table public.documents add column if not exists origin text not null default 'ingested';
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'documents_origin_chk') then
    alter table public.documents add constraint documents_origin_chk check (origin in ('ingested','draft'));
  end if;
end $$;

create or replace function public.save_document(p_payload jsonb, p_actor uuid, p_audit jsonb)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  v_id uuid;
  v_doc_type text := p_payload->>'doc_type';
  v_title    text := p_payload->>'title';
  v_text     text := p_payload->>'extracted_text';
  v_chunk jsonb;
  v_expected int := 0;
  v_norm double precision;
  c_max_chunks constant int := 64;   -- contracts are longer than memories; still a hard fan-out bound
begin
  -- actor: active team member, fail closed (re-validated inside log_activity too)
  if p_actor is null or not exists (select 1 from public.team_members where id = p_actor and active) then
    raise exception 'save_document: actor must be an active team member';
  end if;
  -- strict payload shape
  if exists (select 1 from jsonb_object_keys(p_payload) k where k not in ('doc_type','title','extracted_text','chunks')) then
    raise exception 'save_document: unexpected key in payload';
  end if;
  if v_doc_type is null or v_doc_type not in ('sow','mou','invoice','proposal','brief','runbook','other') then
    raise exception 'save_document: bad doc_type %', v_doc_type;
  end if;
  if jsonb_typeof(p_payload->'title') is distinct from 'string' or v_title = '' or length(v_title) > 300 then
    raise exception 'save_document: title must be a non-empty string <=300 chars';
  end if;
  if jsonb_typeof(p_payload->'extracted_text') is distinct from 'string' or v_text = '' or length(v_text) > 200000 then
    raise exception 'save_document: extracted_text must be a non-empty string <=200000 chars';
  end if;
  if jsonb_typeof(p_payload->'chunks') is distinct from 'array' then raise exception 'save_document: chunks must be an array'; end if;
  if jsonb_array_length(p_payload->'chunks') < 1 then raise exception 'save_document: at least one chunk required'; end if;
  if jsonb_array_length(p_payload->'chunks') > c_max_chunks then raise exception 'save_document: too many chunks (max %)', c_max_chunks; end if;

  -- validate every chunk (contiguous index from 0, non-empty content, 768-dim unit-normalized embedding)
  for v_chunk in select value from jsonb_array_elements(p_payload->'chunks') as value loop
    if not (v_chunk ? 'chunk_index' and v_chunk ? 'content' and v_chunk ? 'embedding' and v_chunk ? 'embedding_model') then raise exception 'save_document: chunk missing a required key'; end if;
    if exists (select 1 from jsonb_object_keys(v_chunk) k where k not in ('chunk_index','content','embedding','embedding_model')) then raise exception 'save_document: unexpected key in chunk'; end if;
    if jsonb_typeof(v_chunk->'chunk_index') <> 'number' then raise exception 'save_document: chunk_index must be a number'; end if;
    if (v_chunk->'chunk_index')::text ~ '[.eE]'
       or (v_chunk->>'chunk_index')::numeric < 0
       or (v_chunk->>'chunk_index')::numeric <> floor((v_chunk->>'chunk_index')::numeric)
       or (v_chunk->>'chunk_index')::numeric > 1000000 then raise exception 'save_document: chunk_index must be a nonnegative integer'; end if;
    if jsonb_typeof(v_chunk->'content') <> 'string' or v_chunk->>'content' = '' then raise exception 'save_document: chunk content must be a non-empty string'; end if;
    if jsonb_typeof(v_chunk->'embedding') <> 'string' then raise exception 'save_document: chunk embedding must be a string'; end if;
    if jsonb_typeof(v_chunk->'embedding_model') <> 'string' or (v_chunk->>'embedding_model') <> 'gemini-embedding-001' then raise exception 'save_document: bad chunk embedding_model'; end if;
    if (v_chunk->>'chunk_index')::int <> v_expected then raise exception 'save_document: non-contiguous chunk_index (expected %)', v_expected; end if;
    if public.vector_dims((v_chunk->>'embedding')::public.vector) <> 768 then raise exception 'save_document: chunk embedding not 768-dim'; end if;
    v_norm := public.vector_norm((v_chunk->>'embedding')::public.vector);
    if v_norm = 0 or abs(v_norm - 1) > 1e-3 then raise exception 'save_document: chunk embedding not unit-normalized (norm=%)', v_norm; end if;
    v_expected := v_expected + 1;
  end loop;

  -- INSERT a NEW draft row (never update/overwrite → cannot touch an ingested final). origin='draft',
  -- created_by = actor, sensitivity left at the table default ('restricted').
  insert into public.documents (doc_type, title, extracted_text, created_by, origin)
    values (v_doc_type::public.doc_kind, v_title, v_text, p_actor, 'draft')
    returning id into v_id;

  insert into public.document_chunks (document_id, chunk_index, content, embedding, embedding_model)
  select v_id, (c->>'chunk_index')::int, c->>'content', (c->>'embedding')::public.vector, c->>'embedding_model'
  from jsonb_array_elements(p_payload->'chunks') as c;

  -- atomic audit in the SAME transaction (re-validates actor + detail); any failure rolls back the insert.
  perform public.log_activity(p_actor, 'document.save_draft', 'documents', v_id, coalesce(p_audit, '{}'::jsonb));
  return v_id;
end $$;

revoke execute on function public.save_document(jsonb, uuid, jsonb) from public, anon, authenticated;
grant  execute on function public.save_document(jsonb, uuid, jsonb) to service_role;
